name: endava_profile_app
description: Endava profile application.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  analyzer: ^0.39.2+1
  json_annotation:
  build_runner:
  provider:
  flutter_cache_manager: ^1.1.3
  equatable: 1.0.3
  bloc: 3.0.0
  flutter_bloc: 3.2.0
  percent_indicator: ^2.1.1
  flutter_keychain: ^1.0.0
  sprintf: ^4.0.0
  flutter_slidable: ^0.5.5
  expandable: ^4.1.2
  shared_preferences: ^0.5.8
  share: ^0.6.5+2
  keyboard_avoider: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Bold.ttf
    - family: ProfileAppIcons
      fonts:
        - asset: assets/fonts/ProfileAppIcons.ttf
